# https://www.redhat.com/en/blog/podman-inside-container

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ovsx-build
spec:
  params:
    - name: source_repo
    - name: builder_image
      default: redhat/ubi9
    - name: devspaces_version
    - name: output_registry
    - name: output_image_namespace
    - name: output_image_tag
    - name: upstream_registry_user
    - name: upstream_registry_password
  steps:
    - name: build-image
      image: $(params.builder_image)
      securityContext:
        privileged: true
      script: |
        dnf install -y podman npm jq git

        podman login registry.redhat.io -u '$(params.upstream_registry_user)' -p '$(params.upstream_registry_password)'

        git clone '$(params.source_repo)' source
        cd source
        ./build-image.sh '$(params.devspaces_version)' '$(params.output_registry)' '$(params.output_image_namespace)' '$(params.output_image_tag)'

        podman push "$OUTPUT_REGISTRY/$OUTPUT_NAMESPACE/pluginregistry-rhel8:$OUTPUT_TAG"
